// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";
let connectionString = process.env.DATABASE_URL;
if (connectionString && process.env.DB_USER && process.env.DB_PASSWORD) {
  connectionString = connectionString.replace(
    /(postgres(?:ql)?:\/\/)[^:]+:[^@]+(@.*)/,
    (_match, p1, p2) => `${p1}${process.env.DB_USER}:${process.env.DB_PASSWORD}${p2}`
  );
}
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: connectionString ?? "",
  },
});
